name: RecoveryMod
main: dev.kcbleeker.recoverymod.RecoveryMod
version: 1.0
api-version: 1.20
commands:
  recover:
    description: Restore a player's last inventory (OP only)
    usage: /recover <PlayerName>
    permission: op
